### ISSUE TITLE
"Network Error (status 422)"

### ISSUE THREAD

**Issue by PnfrlEnm** [beat-machine/beat-webapp#36]
Any time I try to render a song, I just get a warning that says "Network Error (status 422)" and when I click to retry, it just keeps saying it

**Comment by SupremeEditor23** [comment]
Hi, I'm getting a similar issue with a 2min51sec MP3. Status code is 422 like the original poster.

**Comment by VexianEmpire** [comment]
I tried to use a YT video and got this error too. I tried both linking to the video _and_ downloading the video then uploading it to the site

**Comment by VexianEmpire** [comment]
still happens after waiting a few days, so it's not just a one-time issue (song length is 51s)

**Comment by quattroformaggi** [comment]
atm this error is back again

**Comment by branchpanic** [comment]
I haven't been active on this project for a while, but I understand this must be annoying. I just pushed a few small changes that might help.

- The backend is now more lenient on what files it accepts
- YouTube URLs are fixed (they were temporarily disabled at one point for reasons I forget, but a bug was preventing them from working regardless)

Unfortunately, I was never able to reproduce this reliably, so these are my best-guess fixes.

Please let me know if there are any improvements, as I'd like for the site to continue functioning even though I'm not working on new features. Thanks for continuing to use the site.

**Comment by branchpanic** [comment]
Consolidating NetworkError threads: https://github.com/beat-machine/beat-webapp/issues/43
