### ISSUE TITLE
Processing always fails with status 400

### ISSUE THREAD

**Issue by dhsavell** [beat-machine/beat-webapp#37]
Seems to have popped up recently. I will check my Google Cloud configuration when I get a chance. Possibly related to #36.

**Comment by dhsavell** [comment]
@commentspae Apologies for the potential notification spam. I just deployed a new revision, and noticed that MP3 uploads are succeeding but YouTube downloads aren't. Were you trying uploaded songs or YouTube videos?

**Comment by commentspae** [comment]
MP3 files, apparently.

**Comment by dhsavell** [comment]
Did some investigation, but still haven't been able to pinpoint it as a server or library problem. My current guess is that it's the latter. Are you still experiencing the issue with every upload? And if so, what effects and song (if you can share)? Thanks.

**Comment by branchpanic** [comment]
Consolidating NetworkError threads: https://github.com/beat-machine/beat-webapp/issues/43
