### ISSUE TITLE
YouTube importing doesn't work at ALL

### ISSUE THREAD

**Issue by The-ProGrammer66** [beat-machine/beat-webapp#58]
Every time I try to use a YouTube video, it returns error 400. This doesn't seem to occur with audio files.

**Comment by branchpanic** [comment]
This happens because the YouTube downloader gets out of date. I just updated it and was able to download a video afterwards. Post here if you still have issues, thanks.

**Comment by The-ProGrammer66** [comment]
It works now, but it still shows error 400 if enough remixes are made repeatedly.

**Comment by The-ProGrammer66** [comment]
I'm getting error 400 again.

**Comment by The-ProGrammer66** [comment]
nvm it works now
